### ISSUE TITLE
코딩테스트에서 사용하면 좋은 함수 

### ISSUE THREAD

**Issue by bar-d** [Groot-94/CodingTest_Study#2]
### [max()](https://developer.apple.com/documentation/swift/array/max()) 
- 시퀀스의 가장 큰 요소를 반환
- 시퀀스에 값이 없으면 nil을 반환

```swift
let heights = [67.5, 65.7, 64.3, 61.1, 58.5, 60.3, 64.9]
let greatestHeight = heights.max()
print(greatestHeight)
// Prints "Optional(67.5)"
```

`시간복잡도 O(n)`

### [min()](https://developer.apple.com/documentation/swift/array/min()) 
- 시퀀스의 가장 작은 요소를 반환
- 시퀀스에 값이 없으면 nil을 반환

```swift
let heights = [67.5, 65.7, 64.3, 61.1, 58.5, 60.3, 64.9]
let lowestHeight = heights.min()
print(lowestHeight)
// Prints "Optional(58.5)"
```

`시간복잡도 O(n)`

**Comment by bar-d** [comment]
@Groot-94

**Comment by bar-d** [comment]
이전 이슈에도 시간복잡도 넣어주세용

**Comment by Groot-94** [comment]
굿
